apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-secret
type: Opaque
data:
  postgres-exporter-password: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnN1cGVyc2VjcmV0QHBvc3RncmVzOjU0MzIvd2ViYXBwP3NzbG1vZGU9ZGlzYWJsZQ==
