kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-pv
  labels:
    name: mongodb-hostpath
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: mongodb
  hostPath:
    path: /data/pv009
