apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-root-password: c3VwZXJzZWNyZXQ=
  mongodb-exporter-uri: bW9uZ29kYjovL2V4cG9ydGVyOnN1cGVyc2VjcmV0QGxvY2FsaG9zdDoyNzAxNw==
