apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaxrs-hazelcast-quarkus
spec:
  selector:
    matchLabels:
      app: jaxrs-hazelcast-quarkus
  replicas: 1
  template:
    metadata:
      labels:
        app: jaxrs-hazelcast-quarkus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: jaxrs-hazelcast-quarkus
        image: yurak/jaxrs-hazelcast-quarkus:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            port: 8080
            path: /health/live
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            port: 8080
            path: /health/ready
          initialDelaySeconds: 3
          periodSeconds: 3
