version: 2
updates:
  - package-ecosystem: docker
    directory: "/kubernetes/monitoring/test/ab"
    schedule:
      interval: daily
    automerged_updates:
      - match:
        dependency_type: all
        update_type: all
    open-pull-requests-limit: 10
    assignees:
      - yurake
  - package-ecosystem: docker
    directory: "/kubernetes/monitoring/test/postmannewman"
    schedule:
      interval: daily
    automerged_updates:
      - match:
        dependency_type: all
        update_type: all
    open-pull-requests-limit: 10
    assignees:
      - yurake
  - package-ecosystem: docker
    directory: "/kubernetes/postgres"
    schedule:
      interval: daily
    automerged_updates:
      - match:
        dependency_type: all
        update_type: all
    open-pull-requests-limit: 10
    assignees:
      - yurake
  - package-ecosystem: docker
    directory: "/kubernetes/mysql"
    schedule:
      interval: daily
    automerged_updates:
      - match:
        dependency_type: all
        update_type: all
    open-pull-requests-limit: 10
    assignees:
      - yurake
  - package-ecosystem: docker
    directory: "/kubernetes/nginx"
    schedule:
      interval: daily
    automerged_updates:
      - match:
        dependency_type: all
        update_type: all
    open-pull-requests-limit: 10
    assignees:
      - yurake
  - package-ecosystem: docker
    directory: "/kubernetes/mongodb"
    schedule:
      interval: daily
    automerged_updates:
      - match:
        dependency_type: all
        update_type: all
    open-pull-requests-limit: 10
    assignees:
      - yurake
  - package-ecosystem: docker
    directory: "/kubernetes/monitoring/jenkins"
    schedule:
      interval: daily
    automerged_updates:
      - match:
        dependency_type: all
        update_type: all
    open-pull-requests-limit: 10
    assignees:
      - yurake
  - package-ecosystem: docker
    directory: "/kubernetes/wlp"
    schedule:
      interval: daily
    automerged_updates:
      - match:
        dependency_type: all
        update_type: all
    open-pull-requests-limit: 10
    assignees:
      - yurake
  - package-ecosystem: docker
    directory: "/kubernetes/rabbitmq"
    schedule:
      interval: daily
    automerged_updates:
      - match:
        dependency_type: all
        update_type: all
    open-pull-requests-limit: 10
    assignees:
      - yurake
