pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=2"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - base=master
      - check-success=Docker Image CI
      - check-success=Java CI
    actions:
      merge:
        method: merge
