language: java

jdk:
  - openjdk8

script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  - mvn -B package --file application/activemq-mysql-quarkus/pom.xml -Pcoverage 
