language: java
jdk:
- openjdk8
addons:
  sonarcloud:
    organization: yurak
    token:
      secure: "gqQb8A+X75A9YRMqf+aJX9/i54+sBxdkJnYkFceo1uFHuvv3AKiz/tQKVAmb8UWdJCegoE4oFumcrBjsWdM5UrSZtzftGR/0XUg+LMn06k5HfqdXoYLce3SjfHHg3GM7pypILAcxPCHUNwBgFLYaw/GiSVU9LK73ASSRuFLc5O8xg8hFWyQEgthlKOlDVyXuiWeznIBq7PIlFQEVYzfHHQICQnHCtdLYhQtMsUy23vSIzAW4VKHxxvh51dOIFLD2OP8bunjZJYdX576qJQWhr4cO1+DotQ2FEzSYeMKuRsGd90l4WGsxc6W+9VDhaiK8Y4p5OsZSG99zeckPH1lrlddF430HreoZ3JbnHU8zixb1nMxfDaYBujiqxeS7yNeYcnuMDm1JyrVRgAONlcp8j09BPJF9tYKdJ4/GcDkjTMYXdRB311enYvsaMwaxSBvlMkc5msCW8WEExdx8Kbxhi7q4Pgecd0pFb85vgbdNA3QnmpV6RVQ0xxgf8JnOQSMMkDqdnznvtWy6h/OnqLbiflyCmtDr3E3DErF2LjaFY5yTNver8FXoOwOW631I2p8buKe20pSzE+5O4eZ6upsGSuK1iSaBIjPyRVJxwPwyDgWEX69Czek93icX8xaua0aGfYu3bqbCh2p2k1xfk4GDlRqh/2FrboTcae+jLgWYHrg="
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
jobs:
  include:
  - stage: parent-pom
    before_script: cd $TRAVIS_BUILD_DIR/application/parent-pom
    script:
    - mvn clean install
  - stage: webapp-service
    before_script: cd $TRAVIS_BUILD_DIR/application/webapp-service
    script:
    - mvn clean install
  - stage: scheduled-quarkus
    before_script: cd $TRAVIS_BUILD_DIR/application/scheduled-quarkus
    script:
    - mvn clean verify sonar:sonar -Dsonar.projectKey=yurake_k8s-3tier-webapp
