language: java
jdk:
- openjdk8
addons:
  sonarcloud:
    organization: yurak
    token:
      secure: "Q+apkUKnH8KGXYhtJdp4gi3pDUWLzrHFFXuwoonVE/8pxYkG6Zgh67gQTppQFlbEtbS1RwzZuCSQ0LUXXeXqXvUW2yVq6A63HawJh+D5oQnTXI2NlHt7rYJSaiQjA+q6wA1uvPOmyhDRUbgGpLnrKRcoXGTG/bbK5H2MYu/KIY4LU6rUhN6dfA/+aprfs79U72Lfmxxdsr+6jugEre6AkrQcQhaeUtu+JmPyjbEaRo16QHrW/H8/3XjkzeD9DDN6CXnmQQ5TX1ryEt+toPO+nUQD72YQ2AdtODjTlyksavK8/fklHpsxc2TBS2e2jJAmE3t2w2aqENjeYDE6yRnWKhDWgb7AHMBuDkqfx8sdJLDHMGzZcLBgMub9vfcLkNtUzln2aDVwX69aifV9hL2hTgCd26++tgERCxERq7cWtE93bL94OY3h2ClrHwJ+Z/ZpUlBC2Rsau7r0UbZefYx8fRCwaWUpFXc2YsplkHZoBWqeALmZfV2p1GBVO+DogcnfA08J0KeqLR4F6lHgPn8ZqAPjDdz5OIafgzOAK7/lETPZqywLzPf03dcOGKbLlfOl1RGEg+7bBYjWIL54feAs24RJcfRtzaT6ck82ejfXRLcQuQUuAa0Dz3YwffnNahcJiqWZaQgtWY0kte4N5z0bh8ejV8nGsA4Z3Nq4B6Thl48="
cache:
  directories:
  - "${HOME}/.m2/repository"
  - "${HOME}/.sonar/cache"
git:
  depth: false
jobs:
  include:
  - stage: parent-pom
    before_script: cd $TRAVIS_BUILD_DIR/application/parent-pom
    script:
    - mvn clean install -DskipTests=true
  - stage: webapp-service
    before_script: cd $TRAVIS_BUILD_DIR/application/webapp-service
    script:
    - mvn clean install -DskipTests=true
  - stage: scheduled-quarkus
    before_script: cd $TRAVIS_BUILD_DIR/application/scheduled-quarkus
    script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -DskipTests=true -Dsonar.projectKey=yurake_k8s-3tier-webapp
