language: java
jdk:
- openjdk8
addons:
  sonarcloud:
    organization: yurak
    token:
      secure: "${SONAR_TOKEN}"
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
jobs:
  include:
  - stage: parent-pom
    before_script: cd $TRAVIS_BUILD_DIR/application/parent-pom
    script:
    - mvn clean install -DskipTests=true
  - stage: webapp-service
    before_script: cd $TRAVIS_BUILD_DIR/application/webapp-service
    script:
    - mvn clean install -DskipTests=true
  - stage: scheduled-quarkus
    before_script: cd $TRAVIS_BUILD_DIR/application/scheduled-quarkus
    script:
    - mvn clean verify sonar:sonar -DskipTests=true -Dsonar.projectKey=yurake_k8s-3tier-webapp
env:
  global:
    secure: 0QV8hwSf3puQFjh8HUqolo12Roqhfi5+dFMv0H/T9/SXt/1M2CzRlU0lbHRCcJfGvShn8F5OLjaAnh08M+1vp8xlWIJKayvezORAhl+4osLnCRTLn+4zlaeID4JLLP5BdR5B0bohVD5U0qcFJTGIrMKqpkr2M09vZhrYowPA+G39tzXiecT7/MdYbOYQc9PwqtpJ3HWDpk1uZNN3n9+HLoZCSe0l0uMA2oMKMUPqIJJf72G/ZzgFRxfZG74iS8MebFEEY21vvvtG9psqard9DFwMiksYGY7eDF2P9bt6VXha1gQJLpyt4zaqJkX0peaHtQrvEF6ATd5sMNL1MbGdbrgx0CRk5pOqiZKinE1ghBqYgwOM3scv6W8sUvBGhd/bdcTCn1nh0l18KnUoRv2ROiswCX0Rba8kxWfaf9BZuORfzSLvA7xnhL9rVXUlVfMhKUdYf4HBrY1w+PrjrWrX5W03yUSkuYVzXUfcS7xuF5Xvxt3hHHNBuWBOCWT8ulWwBf64fDjFxFviPoDVd4wYzl0w4KKEc7y6gW9SKZi1l7BThQZbGfMfhdrUD78N12qVFb9SoFNMMdIWmVxEnHqVQ8m/RrJ59/fpsZle5HhJjtwCGYM+LtICTnPyP5xSBYhc6oXD3pYDogxtl8CQvkvAVQMnltK4ZDz9u1ILeTZpc6s=
