language: java
sudo: false
install: true

jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "yurak"
    token:
      secure: "IGO4y6KN/imvdi0hjxD/KibADygKNtIngFayPC//byiIJqiRxGxUqDFGHGOkBQuEPdNbw+UsELWMx0dD878qy0Fb8BCQaKiQFg7jIt5APTRchws5uvQxix8409Mzghxq259IKtcfDt6LiPRQRpZsVezBIG8cbIQtIyJqngIlKk1PrVG685Da/rm4KYYih1ZPrKz1ZRLAMzjbd+PfGoLCW6dZVo9wl6s4LKyQcrprbrool0jkvoBjsr6gdf3K+BpdsAyJX7yKMtdrRxWu6I1cpUu2pUzfJX51LsVqlOdU+FSL/8DQ+lS5ivdmR9dd5rLQ9xalSqCkY5zsYoEwx0OpHUXdg5wq+5+DmsPr01Z9yurtH5JsE1dMdzuEIxp18TQdPB1bDorrpqfDBt407Li8oZSeSsfqTDytZYzd6gFeBS7n0eEAEAzBvU5ZjeYbJ9WaejcYzqZemRzDJ65x8UV5/kYlsDSaTHPtmRPjvAZHiTLFpSlYnOqeg4m2NqbxBIUGPB1emYzW25K4bVvE8VguaZvQSFqcOM+9TLm4Qgtn3g8ZOp4zhxAiEYBqb7FHjCQgy1lExVW5voThmv8PX0r5YzLt6BTIOJK3+1XR1I18+67HDwYiL+8rmitjslqkbBxp1kNo9REJOAj38l6+oipXA0dfEtHJ1eI5oNDE/SBBB88="

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

jobs:
  include:
    - stage: parent-pom
      before_script: cd $TRAVIS_BUILD_DIR/application/parent-pom
      script:
        - mvn clean install
    - stage: webapp-service
      before_script: cd $TRAVIS_BUILD_DIR/application/webapp-service
      script:
        - mvn clean install
    - stage: scheduled-quarkus
      before_script: cd $TRAVIS_BUILD_DIR/application/scheduled-quarkus
      script:
        # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
        - mvn clean verify sonar:sonar -Dsonar.projectKey=yurake_k8s-3tier-webapp
