apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq-mysql-quarkus
spec:
  selector:
    matchLabels:
      app: activemq-mysql-quarkus
  replicas: 1
  template:
    metadata:
      labels:
        app: activemq-mysql-quarkus
    spec:
      containers:
      - name: activemq-mysql-quarkus
        image: default/activemq-mysql-quarkus:v0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            port: 8080
            path: /health/live
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            port: 8080
            path: /health/ready
          initialDelaySeconds: 3
          periodSeconds: 3
