apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
spec:
  selector:
    matchLabels:
      app: memcached
  replicas: 1
  template:
    metadata:
      labels:
        app: memcached
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9150"
    spec:
      containers:
      - name: memcached
        image: memcached:1.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 11211
        resources:
          limits:
            memory: 600Mi
            cpu: 500m
          requests:
            memory: 100Mi
            cpu: 100m
      - name: memcached-exporter
        image: prom/memcached-exporter:v0.6.0
        ports:
        - containerPort: 9150
        resources:
          limits:
            memory: 100Mi
            cpu: 200m
          requests:
            memory: 100Mi
            cpu: 50m
