apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-kafka-quarkus
spec:
  selector:
    matchLabels:
      app: producer-kafka-quarkus
  replicas: 1
  template:
    metadata:
      labels:
        app: producer-kafka-quarkus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: producer-kafka-quarkus
          image: yurak/producer-kafka-quarkus:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /health/live
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              port: 8080
              path: /health/ready
            initialDelaySeconds: 3
            periodSeconds: 3
