kind: PersistentVolume
apiVersion: v1
metadata:
  name: jupyter-pv
  namespace: monitoring
  labels:
    app: jupyter
    name: jupyter-hostpath
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: jupyter
  hostPath:
    path: /data/pv007
