apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jupyter
  namespace: monitoring
  labels:
    app: jupyter
spec:
  rules:
    - host: jupyter.minikube
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jupyter
                port:
                  number: 8888
