kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jupyter-pvc
  namespace: monitoring
  labels:
    k8s-3tier-webapp: jupyter
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: jupyter
  selector:
    matchLabels:
      name: jupyter-hostpath
