apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-redis-quarkus
spec:
  selector:
    matchLabels:
      app: consumer-redis-quarkus
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer-redis-quarkus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: consumer-redis-quarkus
          image: yurak/consumer-redis-quarkus:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /health/live
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              port: 8080
              path: /health/ready
            initialDelaySeconds: 3
            periodSeconds: 3
