version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 15eac2dc9551ea8566757f925a7f33f2677d2f9e106785390b872dc1a8bfc042
    docker:
      - image: 'cimg/openjdk:11.0.6'
    steps:
      - checkout
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/parent-pom/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run: 
          name: Run tests parent-pom
          working_directory: application/parent-pom
          command: |
            mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/parent-pom/pom.xml" }}
      - store_artifacts:
          path: application/parent-pom/target
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/webapp-service/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run: 
          name: Run tests webapp-service
          working_directory: application/webapp-service
          command: |
            ../../cc-test-reporter before-build
            mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true
            ../../cc-test-reporter format-coverage target/site/jacoco/jacoco.xml -t jacoco
            ../../cc-test-reporter upload-coverage
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/webapp-service/pom.xml" }}
      - store_artifacts:
          path: application/webapp-service/target
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/consumer-activemq-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run: 
          name: Run tests consumer-activemq-quarkus
          working_directory: application/consumer-activemq-quarkus
          command: |
            ../../cc-test-reporter before-build
            mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true
            ../../cc-test-reporter format-coverage target/site/jacoco/jacoco.xml -t jacoco
            ../../cc-test-reporter upload-coverage
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/consumer-activemq-quarkus/pom.xml" }}
      - store_artifacts:
          path: application/consumer-activemq-quarkus/target
