version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
jobs:
  build:
    docker:
      - image: "cimg/openjdk:14.0.1"
    steps:
      - checkout
      - sonarcloud/scan
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/parent-pom/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests parent-pom
          working_directory: application/parent-pom
          command: mvn clean install
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/parent-pom/pom.xml" }}
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/webapp-service/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests webapp-service
          working_directory: application/webapp-service
          command: mvn clean verify sonar:sonar
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/webapp-service/pom.xml" }}

      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/consumer-activemq-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests consumer-activemq-quarkus
          working_directory: application/consumer-activemq-quarkus
          command: mvn clean verify sonar:sonar -Dsonar.projectKey=yurake_consumer-activemq-quarkus
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/consumer-activemq-quarkus/pom.xml" }}

      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/consumer-hazelcast-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests consumer-hazelcast-quarkus
          working_directory: application/consumer-hazelcast-quarkus
          command: mvn clean verify sonar:sonar -Dsonar.projectKey=yurake_consumer-hazelcast-quarkus
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/consumer-hazelcast-quarkus/pom.xml" }}

      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/consumer-kafka-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests consumer-kafka-quarkus
          working_directory: application/consumer-kafka-quarkus
          command: mvn clean verify sonar:sonar -Dsonar.projectKey=yurake_consumer-kafka-quarkus
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/consumer-kafka-quarkus/pom.xml" }}

      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/consumer-rabbitmq-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests consumer-rabbitmq-quarkus
          working_directory: application/consumer-rabbitmq-quarkus
          command: mvn clean verify sonar:sonar -Dsonar.projectKey=yurake_consumer-rabbitmq-quarkus
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/consumer-rabbitmq-quarkus/pom.xml" }}

      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/consumer-redis-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests consumer-redis-quarkus
          working_directory: application/consumer-redis-quarkus
          command: mvn clean verify sonar:sonar -Dsonar.projectKey=yurake_consumer-redis-quarkus
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/consumer-redis-quarkus/pom.xml" }}

      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-activemq-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests jaxrs-activemq-quarkus
          working_directory: application/jaxrs-activemq-quarkus
          command: mvn clean verify sonar:sonar -Dsonar.projectKey=yurake_jaxrs-activemq-quarkus
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-activemq-quarkus/pom.xml" }}

      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-hazelcast-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests jaxrs-hazelcast-quarkus
          working_directory: application/jaxrs-hazelcast-quarkus
          command: mvn clean verify sonar:sonar -Dsonar.projectKey=yurake_jaxrs-hazelcast-quarkus
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-hazelcast-quarkus/pom.xml" }}

      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-kafka-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests jaxrs-kafka-quarkus
          working_directory: application/jaxrs-kafka-quarkus
          command: mvn clean verify sonar:sonar -Dsonar.projectKey=yurake_jaxrs-kafka-quarkus

      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-kafka-quarkus/pom.xml" }}

      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-memcached-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests jaxrs-memcached-quarkus
          working_directory: application/jaxrs-memcached-quarkus
          command: mvn clean verify sonar:sonar -Dsonar.projectKey=yurake_jaxrs-memcached-quarkus
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-memcached-quarkus/pom.xml" }}

      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-mongodb-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests jaxrs-mongodb-quarkus
          working_directory: application/jaxrs-mongodb-quarkus
          command: mvn clean verify sonar:sonar -Dsonar.projectKey=yurake_jaxrs-mongodb-quarkus
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-mongodb-quarkus/pom.xml" }}

      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-mysql-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests jaxrs-mysql-quarkus
          working_directory: application/jaxrs-mysql-quarkus
          command: mvn clean verify sonar:sonar -Dsonar.projectKey=yurake_jaxrs-mysql-quarkus
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-mysql-quarkus/pom.xml" }}

      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-postgres-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests jaxrs-postgres-quarkus
          working_directory: application/jaxrs-postgres-quarkus
          command: mvn clean verify sonar:sonar -Dsonar.projectKey=yurake_jaxrs-postgres-quarkus
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-postgres-quarkus/pom.xml" }}

      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-rabbitmq-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests jaxrs-rabbitmq-quarkus
          working_directory: application/jaxrs-rabbitmq-quarkus
          command: mvn clean verify sonar:sonar -Dsonar.projectKey=yurake_jaxrs-rabbitmq-quarkus
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-rabbitmq-quarkus/pom.xml" }}

      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-redis-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests jaxrs-redis-quarkus
          working_directory: application/jaxrs-redis-quarkus
          command: mvn clean verify sonar:sonar -Dsonar.projectKey=yurake_jaxrs-redis-quarkus
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/jaxrs-redis-quarkus/pom.xml" }}

      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/producer-kafka-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests producer-kafka-quarkus
          working_directory: application/producer-kafka-quarkus
          command: mvn clean verify sonar:sonar -Dsonar.projectKey=yurake_producer-kafka-quarkus
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/producer-kafka-quarkus/pom.xml" }}

      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/randompublish-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests randompublish-quarkus
          working_directory: application/randompublish-quarkus
          command: mvn clean verify sonar:sonar -Dsonar.projectKey=yurake_randompublish-quarkus
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/randompublish-quarkus/pom.xml" }}

      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/redis-mysql-helidon/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests redis-mysql-helidon
          working_directory: application/redis-mysql-helidon
          command: mvn clean verify sonar:sonar -Dsonar.projectKey=yurake_redis-mysql-helidon
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/redis-mysql-helidon/pom.xml" }}

      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/scheduled-quarkus/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests scheduled-quarkus
          working_directory: application/scheduled-quarkus
          command: mvn clean verify sonar:sonar -Dsonar.projectKey=yurake_scheduled-quarkus
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/scheduled-quarkus/pom.xml" }}

      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "application/wlp-web-java-spring/pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Run tests wlp-web-java-spring
          working_directory: application/wlp-web-java-spring
          command: mvn clean verify sonar:sonar -Dsonar.projectKey=yurake_wlp-web-java-spring
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "application/wlp-web-java-spring/pom.xml" }}
workflows:
  main:
    jobs:
      - build:
          context: sonarcloud
