apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: nginx.minikube
    http:
      paths:
      - path:
        backend:
          serviceName: nginx
          servicePort: 80
