apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: k8s.3tier.webapp
    http:
      paths:
      - path: /docs
        backend:
          serviceName: nginx
          servicePort: 80
