kind: PersistentVolume
apiVersion: v1
metadata:
  name: activemq-pv
  labels:
    name: activemq-hostpath
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: activemq
  hostPath:
    path: /data/pv010
