apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq
spec:
  selector:
    matchLabels:
      app: activemq
  replicas: 1
  template:
    metadata:
      labels:
        app: activemq
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9404"
    spec:
      containers:
      - name: activemq
        image: vromero/activemq-artemis:2.11.0-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8161
        - containerPort: 9404
        - containerPort: 61616
        env:
        - name: ENABLE_JMX_EXPORTER
          value: "true"
        - name: JAVA_OPTS
          value: "-Duser.timezone=Asia/Tokyo"
        volumeMounts:
        - name: activemq-persistent-storage
          mountPath: /var/lib/artemis
      volumes:
      - name: activemq-persistent-storage
        persistentVolumeClaim:
          claimName: activemq-pvc
