kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: activemq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: activemq
  selector:
    matchLabels:
      name: activemq-hostpath
