apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq
spec:
  selector:
    matchLabels:
      app: activemq
  replicas: 1
  template:
    metadata:
      labels:
        app: activemq
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9404"
    spec:
      containers:
      - name: activemq
        image: vromero/activemq-artemis:2.11.0-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8161
        - containerPort: 9404
        - containerPort: 61616
        resources:
          limits:
            memory: 600Mi
            cpu: 500m
          requests:
            memory: 100Mi
            cpu: 100m
        env:
        - name: ENABLE_JMX_EXPORTER
          value: "true"
