apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-mysql-quarkus
spec:
  selector:
    matchLabels:
      app: hazelcast-mysql-quarkus
  replicas: 1
  template:
    metadata:
      labels:
        app: hazelcast-mysql-quarkus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: hazelcast-mysql-quarkus
        image: yurak/hazelcast-mysql-quarkus:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            port: 8080
            path: /health/live
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            port: 8080
            path: /health/ready
          initialDelaySeconds: 3
          periodSeconds: 3
