apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9104"
    spec:
      containers:
      - name: mysql
        image: default/mysql:v0.0.1
        imagePullPolicy: IfNotPresent
        args:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        ports:
        - name: mysql
          containerPort: 3306
        resources:
          limits:
            memory: 600Mi
            cpu: 500m
          requests:
            memory: 100Mi
            cpu: 100m
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: tz
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      - name: mysql-exporter
        image: prom/mysqld-exporter:v0.12.1
        ports:
        - containerPort: 9104
        resources:
          limits:
            memory: 100Mi
            cpu: 200m
          requests:
            memory: 100Mi
            cpu: 50m
        env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-exporter-password
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
