apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
    spec:
      containers:
      - name: redis-master
        image: redis:5.0.6
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: 600Mi
            cpu: 200m
          requests:
            memory: 100Mi
            cpu: 50m
      - name: redis-exporter
        image: oliver006/redis_exporter:v1.3.5-alpine
        ports:
        - containerPort: 9121
        resources:
          limits:
            memory: 100Mi
            cpu: 200m
          requests:
            memory: 100Mi
            cpu: 100m
