apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  rules:
    - host: prometheus.minikube
      http:
        paths:
          - path:
            backend:
              serviceName: prometheus
              servicePort: 9090
