kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pv
  namespace: monitoring
  labels:
    app: jenkins
    name: jenkins-hostpath
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: jenkins
  hostPath:
    path: /data/pv006
