apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mycluster.icp:8500/default/docker_hub_id/mysql:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
