apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wlp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: k8s.3tier.webapp
    http:
      paths:
      - path:
        backend:
          serviceName: wlp
          servicePort: 9080
