apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wlp
spec:
  rules:
    - host: wlp.minikube
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wlp
                port:
                  number: 9080
