apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wlp
spec:
  rules:
  - host: wlp.minikube
    http:
      paths:
      - path: /
        backend:
          serviceName: wlp
          servicePort: 9080
