apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-consumer
spec:
  selector:
    matchLabels:
      app: rabbitmq-consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq-consumer
    spec:
      containers:
      - name: rabbitmq-consumer
        image: default/rabbitmq-consumer:v0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9081
