apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hazelcast
  labels:
    app: hazelcast
spec:
  replicas: 1
  serviceName: hazelcast
  selector:
    matchLabels:
      app: hazelcast
  template:
    metadata:
      labels:
        app: hazelcast
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: hazelcast
        image: default/hazelcast:v0.0.1
        ports:
        - containerPort: 5701
        - containerPort: 8080
        env:
        - name: PROMETHEUS_PORT
          value: "8080"
