apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-mysql-helidon
spec:
  selector:
    matchLabels:
      app: redis-mysql-helidon
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-mysql-helidon
    spec:
      containers:
      - name: redis-mysql-helidon
        image: default/redis-mysql-helidon:v0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
