name: Check for CI Target

on:
  push:
    branches:
      - master
  pull_request:
  issues:
    types: [closed]

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get the current number of java pcojects
        working-directory: ./application
        run: echo ::set-env name=SOURCE_PROJECT::$(find . -name "pom.xml" | grep -v -e target -e src | wc -l | tr -d ' ')
      - name: get java-ci.yml
        working-directory: ./.github/workflows
        run: echo ::set-env name=JAVACI_PROJECT::$(grep verify java-ci.yml | wc -l | tr -d ' ')
      - name: check java-ci.yml
        run: |
          echo CURRENT: ${SOURCE_PROJECT}
          echo TARGET: ${JAVACI_PROJECT}
          test ${SOURCE_PROJECT} = ${JAVACI_PROJECT}
