name: Check for Update

on:
  push:
    branches:
      - master
  pull_request:
  issues:
    types: [closed]

jobs:
  minikube-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check current minikube version
        working-directory: ./.github/workflows
        run: echo ::set-env name=SOURCE_VERSION::$(grep "minikube:" minikube-ci.yml | awk '{print $3}' | tr -d ])
      - name: check latest tag minikube version
        run: echo ::set-env name=TARGET_VERSION::$(curl -s https://api.github.com/repos/kubernetes/minikube/releases | jq -r '.[].tag_name' | grep -v '-' | sort -t'.' -k2,2n | tail -n 1 | tr -d 'v')
      - name: check diff
        run: |
          echo CURRENT: ${SOURCE_VERSION}
          echo TARGET: ${TARGET_VERSION}
          test ${SOURCE_VERSION} = ${TARGET_VERSION}
      - name: check current minikube version
        working-directory: ./.github/workflows
        run: echo ::set-env name=SOURCE_VERSION::$(grep "minikube:" minikube-stress-ci.yml | awk '{print $3}' | tr -d ])
      - name: check diff stress
        run: |
          echo CURRENT: ${SOURCE_VERSION}
          echo TARGET: ${TARGET_VERSION}
          test ${SOURCE_VERSION} = ${TARGET_VERSION}
      - name: check current minikube version
        working-directory: ./.github/workflows
        run: echo ::set-env name=SOURCE_VERSION::$(grep "minikube:" minikube-security-ci.yml | awk '{print $3}' | tr -d ])
      - name: check diff security
        run: |
          echo CURRENT: ${SOURCE_VERSION}
          echo TARGET: ${TARGET_VERSION}
          test ${SOURCE_VERSION} = ${TARGET_VERSION}
  kubernetes-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check current kubernetes version
        working-directory: ./.github/workflows
        run: echo ::set-env name=SOURCE_VERSION::$(grep "kubernetes:" minikube-ci.yml | awk '{print $3}' | tr -d ])
      - name: check latest tag kubernetes version
        run: echo ::set-env name=TARGET_VERSION::$(curl -s https://api.github.com/repos/kubernetes/kubernetes/releases | jq -r '.[].tag_name' | grep -v '-' | sort -t'.' -k2,2n | tail -n 1 | tr -d 'v')
      - name: check diff
        run: |
          echo CURRENT: ${SOURCE_VERSION}
          echo TARGET: ${TARGET_VERSION}
          test ${SOURCE_VERSION} = ${TARGET_VERSION}
      - name: check current kubernetes version
        working-directory: ./.github/workflows
        run: echo ::set-env name=SOURCE_VERSION::$(grep "kubernetes:" minikube-stress-ci.yml | awk '{print $3}' | tr -d ])
      - name: check diff stress
        run: |
          echo CURRENT: ${SOURCE_VERSION}
          echo TARGET: ${TARGET_VERSION}
          test ${SOURCE_VERSION} = ${TARGET_VERSION}
      - name: check current kubernetes version
        working-directory: ./.github/workflows
        run: echo ::set-env name=SOURCE_VERSION::$(grep "kubernetes:" minikube-security-ci.yml | awk '{print $3}' | tr -d ])
      - name: check diff security
        run: |
          echo CURRENT: ${SOURCE_VERSION}
          echo TARGET: ${TARGET_VERSION}
          test ${SOURCE_VERSION} = ${TARGET_VERSION}
