name: Check for Update

on:
  push:
    paths:
      - ".github/workflows/check-for-update.yml"
  pull_request:
  issues:
    types: [closed]

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: check current quarkus version
      working-directory: ./application/parent-pom/
      run: echo ::set-env name=SOURCE_VERSION::$(mvn -q -Dexec.executable=echo -Dexec.args='${quarkus.version}' --non-recursive exec:exec)
    - name: check latest tag quarkus version
      run: echo ::set-env name=TARGET_VERSION::$(curl -s https://api.github.com/repos/quarkusio/quarkus/releases/latest | jq '.tag_name' | tr -d '"')
    - name: check diff
      run: |
        echo CURRENT: ${SOURCE_VERSION}
        echo TARGET: ${TARGET_VERSION}
        test ${SOURCE_VERSION} = ${TARGET_VERSION}

  minikube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: check current quarkus version
      working-directory: ./.github/workflows
      run: echo ::set-env name=SOURCE_VERSION::$(grep "minikube:" minikube-ci.yml | awk '{print $3}' | tr -d ])
    - name: check latest tag quarkus version
      run: echo ::set-env name=TARGET_VERSION::$( curl -s https://api.github.com/repos/kubernetes/minikube/releases/latest | jq '.tag_name' | tr -d '"')
    - name: check diff
      run: |
        echo CURRENT: ${SOURCE_VERSION}
        echo TARGET: ${TARGET_VERSION}
        test ${SOURCE_VERSION} = ${TARGET_VERSION}
    - name: create issue if failure
      if: failure()
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/ISSUE_TEMPLATE/check-for-update-failure.md
    - run: 'echo Created issue number ${{ steps.create-issue.outputs.number }}'
    - run: 'echo Created ${{ steps.create-issue.outputs.url }}'
