name: Docker Image Scan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t default/wlp:v0.0.1 .docker build -f ./kubernetes/wlp/Dockerfile .
