name: Docker Image CI

on:
  push:
    branches:
      - master
    paths:
      - "kubernetes/**"
      - ".github/workflows/docker-image-ci.yml"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: setup docker actions
        env:
          TZ: "Asia/Tokyo"
        run: |
          echo ::set-env name=BUILD_DATE::$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo ::set-env name=VCS_REF::$(echo ${GITHUB_SHA} | cut -c1-8)

      - name: docker login
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
        run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS

      - name: Build image - nginx
        working-directory: ./kubernetes/nginx
        run: docker build -t yurak/nginx:latest
          --build-arg VCS_REF=${VCS_REF}
          --build-arg BUILD_DATE=${BUILD_DATE} .
      - name: Push Image - nginx
        if: github.event_name == 'push'
        run: docker push yurak/nginx:latest
      - name: Update Microbadger
        run: curl -X POST -d {} https://hooks.microbadger.com/images/yurak/nginx/7QCS0ho29O-wTHs3nIw5N2XZls8=

      - name: Build image - mysql
        working-directory: ./kubernetes/mysql
        run: docker build -t yurak/mysql:latest
          --build-arg VCS_REF=${VCS_REF}
          --build-arg BUILD_DATE=${BUILD_DATE} .
      - name: Push Image - mysql
        if: github.event_name == 'push'
        run: docker push yurak/mysql:latest
      - name: Update Microbadger
        run: curl -X POST -d {} https://hooks.microbadger.com/images/yurak/mysql/VdV3GfTNPegsi3iEgCzrSp7fcso=

      - name: Build image - postgres
        working-directory: ./kubernetes/postgres
        run: docker build -t yurak/postgres:latest
          --build-arg VCS_REF=${VCS_REF}
          --build-arg BUILD_DATE=${BUILD_DATE} .
      - name: Push Image - postgres
        if: github.event_name == 'push'
        run: docker push yurak/postgres:latest
      - name: Update Microbadger
        run: curl -X POST -d {} https://hooks.microbadger.com/images/yurak/postgres/buxVcrUNzGrKjvWm2_-mvfW5OHc=

      - name: Build image - mongodb
        working-directory: ./kubernetes/mongodb
        run: docker build -t yurak/mongodb:latest
          --build-arg VCS_REF=${VCS_REF}
          --build-arg BUILD_DATE=${BUILD_DATE} .
      - name: Push Image - mongodb
        if: github.event_name == 'push'
        run: docker push yurak/mongodb:latest
      - name: Update Microbadger
        run: curl -X POST -d {} https://hooks.microbadger.com/images/yurak/mongodb/UMosuG9BuAvvnGJ9gWcSzgBjC5k=

      - name: Build image - rabbitmq
        working-directory: ./kubernetes/rabbitmq
        run: docker build -t yurak/rabbitmq:latest
          --build-arg VCS_REF=${VCS_REF}
          --build-arg BUILD_DATE=${BUILD_DATE} .
      - name: Push Image - rabbitmq
        if: github.event_name == 'push'
        run: docker push yurak/rabbitmq:latest
      - name: Update Microbadger
        run: curl -X POST -d {} https://hooks.microbadger.com/images/yurak/rabbitmq/aN6TGvG8Z9g5SxT7PsSAS5ruys0=

      - name: Build image - jenkins
        working-directory: ./kubernetes/monitoring/jenkins
        run: docker build -t yurak/jenkins:latest
          --build-arg VCS_REF=${VCS_REF}
          --build-arg BUILD_DATE=${BUILD_DATE} .
      - name: Push Image - jenkins
        if: github.event_name == 'push'
        run: docker push yurak/jenkins:latest
      - name: Update Microbadger
        run: curl -X POST -d {} https://hooks.microbadger.com/images/yurak/jenkins/9IhdDnEDW1zwZc2v7l7DWfYTZ4E=

      - name: Build image - ab
        working-directory: ./kubernetes/monitoring/test/ab
        run: docker build -t yurak/ab:latest
          --build-arg VCS_REF=${VCS_REF}
          --build-arg BUILD_DATE=${BUILD_DATE} .
      - name: Push Image - ab
        if: github.event_name == 'push'
        run: docker push yurak/ab:latest
      - name: Update Microbadger
        run: curl -X POST -d {} https://hooks.microbadger.com/images/yurak/ab/Rd4WPZ1EPQWA2KTQwML6JyKoNgc=

      - name: Build image - postmannewman
        working-directory: ./kubernetes/monitoring/test/postmannewman
        run: docker build -t yurak/postmannewman:latest
          --build-arg VCS_REF=${VCS_REF}
          --build-arg BUILD_DATE=${BUILD_DATE} .
      - name: Push Image - postmannewman
        if: github.event_name == 'push'
        run: docker push yurak/postmannewman:latest
      - name: Update Microbadger
        run: curl -X POST -d {} https://hooks.microbadger.com/images/yurak/postmannewman/JYNTOrYaF6nvNQVKCj1BGP1yBpM=
