name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
      
    - name: Build the Docker image - mysql
      working-directory: ./kubernetes/mysql
      run: docker build -t default/mysql:v0.0.1 .
      
    - name: Build the Docker image - nginx
      working-directory: ./kubernetes/nginx
      run: docker build -t default/nginx:v0.0.1 .
      
    - name: Build the Docker image - postgres
      working-directory: ./kubernetes/postgres
      run: docker build -t default/postgres:v0.0.1 .
      
    - name: Build the Docker image - rabbitmq
      working-directory: ./kubernetes/rabbitmq
      run: docker build -t default/rabbitmq:v0.0.1 .
