name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v1
      
    - name: Build the Docker image: wlp
      working-directory: ./kubernetes/wlp
      run: docker build -t default/wlp:v0.0.1 -f .
    
