name: Docker Vulnerability Scan

on:
  push:
    paths:
    - 'application/**'
    - 'kubernetes/**'
    - '.github/workflows/docker-vulnerability-scan.yml'
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        docker_image: [mysql, postgres, mongodb, jaxrs-memcached-quarkus, jaxrs-rabbitmq-quarkus, rabbitmq-mysql-quarkus, postmannewman, ab, jenkins, rabbitmq, nginx, jaxrs-mongodb-quarkus, activemq-mysql-quarkus, jaxrs-mysql-quarkus, randompublish-quarkus, 
jaxrs-activemq-quarkus, scheduled-quarkus, jaxrs-postgres-quarkus, wlp, jaxrs-hazelcast-quarkus, hazelcast-mysql-quarkus, jaxrs-redis-quarkus, redis-mysql-quarkus, redis-mysql-helidon]

    steps:
      - name: Pull docker image
        run: docker pull yurak/${{ matrix.docker_image }}

      - uses: homoluctus/gitrivy@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: yurak/${{ matrix.docker_image }}
          issue: 'true'
          severity: CRITICAL
          issue_assignee: yurake
