name: Docker Vulnerability Scan

on:
  push:
    paths:
    - 'application/**'
    - 'kubernetes/**'
    - '.github/workflows/docker-vulnerability-scan.yml'
  pull_request:

jobs:
  scan:
    name: Daily Vulnerability Scan
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        docker_image: [mysql, postgres, mongodb]

    steps:
      - name: Pull docker image
        run: docker pull yurak/${{ matrix.docker_image }}

      - uses: homoluctus/gitrivy@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: yurak/${{ matrix.docker_image }}
          issue: 'true'
          severity: CRITICAL
          issue_assignee: yurake
