name: Docker Image Scan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      working-directory: ./kubernetes/wlp
      run: docker build -t default/wlp:v0.0.1  -f Dockerfile .
