on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

name: Assign issues to project
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issues to project
        uses: technote-space/create-project-card-action@v1
        with:
          PROJECT: Feature request
          COLUMN: To do
