name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: docker login
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
      run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
      
    - name: Build with Maven - webapp-service
      working-directory: ./application/webapp-service
      run: mvn -B package
      
    - name: Deploy to Github Package Registry - webapp-service
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "<settings><servers><server><id>github</id><username>OWNER</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > settings.xml
        mvn deploy --settings settings.xml --file application/webapp-service/pom.xml

    - name: Maven Build - activemq-mysql-quarkus
      working-directory: ./application/activemq-mysql-quarkus
      run: mvn -B package
    - name: Build Image - activemq-mysql-quarkus
      working-directory: ./application/activemq-mysql-quarkus
      run: docker build -t yurak/activemq-mysql-quarkus:latest -f src/main/docker/Dockerfile.jvm .
    - name: Push Image - activemq-mysql-quarkus
      run: docker push yurak/activemq-mysql-quarkus:latest
      
    - name: Maven Build - hazelcast-mysql-quarkus
      working-directory: ./application/hazelcast-mysql-quarkus
      run: mvn -B package
    - name: Build Image - hazelcast-mysql-quarkus
      working-directory: ./application/hazelcast-mysql-quarkus
      run: docker build -t yurak/hazelcast-mysql-quarkus:latest -f src/main/docker/Dockerfile.jvm .
    - name: Push Image - hazelcast-mysql-quarkus
      run: docker push yurak/hazelcast-mysql-quarkus:latest
      
    - name: Build with Maven - jaxrs-activemq-quarkus
      working-directory: ./application/jaxrs-activemq-quarkus
      run: mvn -B package
      
    - name: Build with Maven - rabbitmq-mysql-quarkus
      working-directory: ./application/rabbitmq-mysql-quarkus
      run: mvn -B package
      
    - name: Build with Maven - randompublish-quarkus
      working-directory: ./application/randompublish-quarkus
      run: mvn -B package
      
    - name: Build with Maven - redis-mysql-helidon
      working-directory: ./application/redis-mysql-helidon
      run: mvn -B package
      
    - name: Build with Maven - redis-mysql-quarkus
      working-directory: ./application/redis-mysql-quarkus
      run: mvn -B package
      
    - name: Build with Maven - scheduled-quarkus
      working-directory: ./application/scheduled-quarkus
      run: mvn -B package
    - name: Build with Maven - wlp-web-java-spring
      working-directory: ./application/wlp-web-java-spring
      run: mvn -B package
      
    - name: Build with Maven - redis-mysql-quarkus
      working-directory: ./application/redis-mysql-quarkus
      run: mvn -B package

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Copy war file
      uses: canastro/copy-file-action@master
      with:
        source: "application/wlp-web-java-spring/target/spring.war"
        target: "kubernetes/wlp/spring.war"
 
    - name: Build the Docker image - wlp
      working-directory: ./kubernetes/wlp
      run: docker build -t default/wlp:v0.0.1 .
