name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build with Maven - webapp-service
      run: mvn -B package --file application/webapp-service/pom.xml
    - name: Deploy to Github Package Registry - webapp-service
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "<settings><servers><server><id>github</id><username>OWNER</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > settings.xml
        mvn deploy --settings settings.xml --file application/webapp-service/pom.xml

    - name: Build with Maven - activemq-mysql-quarkus
      run: mvn -B package --file application/activemq-mysql-quarkus/pom.xml
    - name: Build with Maven - hazelcast-mysql-quarkus
      run: mvn -B package --file application/hazelcast-mysql-quarkus/pom.xml
    - name: Build with Maven - jaxrs-quarkus
      run: mvn -B package --file application/jaxrs-quarkus/pom.xml
    - name: Build with Maven - rabbitmq-consumer
      run: mvn -B package --file application/rabbitmq-consumer/pom.xml
    - name: Build with Maven - randompublish-quarkus
      run: mvn -B package --file application/randompublish-quarkus/pom.xml
    - name: Build with Maven - redis-mysql-helidon
      run: mvn -B package --file application/redis-mysql-helidon/pom.xml
    - name: Build with Maven - redis-mysql-quarkus
      run: mvn -B package --file application/redis-mysql-quarkus/pom.xml
    - name: Build with Maven - scheduled-quarkus
      run: mvn -B package --file application/scheduled-quarkus/pom.xml
    - name: Build with Maven - wlp-web-java-spring
      run: mvn -B package --file application/wlp-web-java-spring/pom.xml
    - name: Build with Maven - redis-mysql-quarkus
      run: mvn -B package --file application/redis-mysql-quarkus/pom.xml
      
