name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven - rabbitmq-consumer
      run: mvn -B package --file application/rabbitmq-consumer/pom.xml
    - name: Build with Maven - jaxrs-mysql-quarkus
      run: mvn -B package --file application/jaxrs-mysql-quarkus/pom.xml
    - name: Build with Maven - wlp-web-java-spring
      run: mvn -B package --file application/wlp-web-java-spring/pom.xml
    - name: Build with Maven - redis-mysql-quarkus
      run: mvn -B package --file application/redis-mysql-quarkus/pom.xml
