name: e2e Test on Minikube

on:
  push:
    paths:
      - "application/**"
      - "kubernetes/**"
      - ".github/workflows/minikube-ci.yml"
  pull_request:

jobs:
  minikube:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup minikube
        uses: manusa/actions-setup-minikube@v1.0.1
        with:
          minikube version: "v1.5.2"
          kubernetes version: "v1.16.2"
      - name: minikube addon settings
        run: |
          sudo /home/runner/work/_temp/minikube addons enable ingress
          sudo /home/runner/work/_temp/minikube addons list
      - name: apply minimal service
        run: |
          sudo sh ./kubernetes/apply-default-minimal.sh
      - name: check before test
        run: |
          sudo kubectl wait --for=condition=available --timeout=1h deployment/nginx
          sudo kubectl wait --for=condition=Ready --timeout=1h pod/$(sudo kubectl get pods | awk '{print $1}' | grep jaxrs-activemq)
          sudo kubectl get nodes
          sudo kubectl get all
          sudo kubectl get all -n monitoring
          sudo kubectl get ingress
          sudo kubectl describe po $(sudo kubectl get pods | awk '{print $1}' | grep mongodb | grep -v jaxrs)
          sudo kubectl logs $(sudo kubectl get pods | awk '{print $1}' | grep jaxrs-activemq)
      - name: e2e test
        run: |
          sudo kubectl apply -f kubernetes/monitoring/test/postmannewman/postmannewman-job.yaml
          sleep 300
          echo "### postmannewman-job ###"
          sudo kubectl -n monitoring logs $(kubectl get pods -n monitoring | awk '{print $1}' | grep postmannewman-job)
          echo "### jaxrs-activemq ###"
          sudo kubectl -n monitoring logs $(kubectl get pods -n monitoring | awk '{print $1}' | grep jaxrs-activemq)
          echo "### jaxrs-mysql ###"
          sudo kubectl -n monitoring logs $(kubectl get pods -n monitoring | awk '{print $1}' | grep jaxrs-mysql)
          echo "### jaxrs-postgres ###"
          sudo kubectl -n monitoring logs $(kubectl get pods -n monitoring | awk '{print $1}' | grep jaxrs-postgres)
          echo "### jaxrs-mongodb ###"
          sudo kubectl -n monitoring logs $(kubectl get pods -n monitoring | awk '{print $1}' | grep jaxrs-mongodb)
          echo "### waiting for complete job ... ###"
          sudo kubectl -n monitoring wait --for=condition=complete --timeout=10m job/postmannewman-job
          sudo kubectl -n monitoring describe job postmannewman-job
          sudo kubectl -n monitoring logs -f $(kubectl get pods -n monitoring | awk '{print $1}' | grep postmannewman-job)
          sudo kubectl get po --all-namespaces=true
