name: e2e test on Minikube
on:
  push:
    paths: 
      - '.github/workflows/minikube-ci.yml'
  pull_request:

jobs:
  minikube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v1.0.1
        with:
          minikube version: 'v1.5.2'
          kubernetes version: 'v1.16.2'
      - name: Interact with the cluster
        run: |
          kubectl get nodes
          ./kubernetes/apply.sh
          kubectl get po --all-namespaces=true
