name: e2e test on Minikube

on:
  push:
    paths:
      - "application/**"
      - "kubernetes/**"
      - ".github/workflows/minikube-ci.yml"
  pull_request:

jobs:
  minikube:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup minikube
        uses: manusa/actions-setup-minikube@v1.0.1
        with:
          minikube version: "v1.5.2"
          kubernetes version: "v1.16.2"
      - name: minikube settings
        run: |
          minikube addons list
          sudo minikube addons enable ingress
          minikube addons list
      - name: apply service
        run: |
          kubectl get nodes
          ./kubernetes/apply.sh
          kubectl get po --all-namespaces=true
      - name: e2e test
        run: |
          kubectl apply -f kubernetes/monitoring/test/postmannewman/postmannewman-job.yaml
          kubectl -n monitoring wait --for=condition=complete --timeout=600s job/postmannewman-job
          kubectl -n monitoring describe job postmannewman-job
          kubectl -n monitoring logs -f $(kubectl get pods -n monitoring | awk '{print $1}' | grep postmannewman-job)
          kubectl get po --all-namespaces=true
