name: Shell Validator

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master
      - name: Run sh-checker
        uses: luizm/action-sh-checker@v0.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sh_checker_comment: true
      - name: Run shellCheck-action
        uses: fearphage/shellcheck-action@0.0.4
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
