name: Yaml Validator

on: [push, pull_request]

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate yaml manifests
        uses: instrumenta/kubeval-action@master
        with:
          files: kubernetes
