kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    name: postgres-hostpath
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: postgres
  hostPath:
    path: /data/pv008
