apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-password: c3VwZXJzZWNyZXQ=
  postgres-exporter-password: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnN1cGVyc2VjcmV0QGxvY2FsaG9zdDo1NDMyL3dlYmFwcD9zc2xtb2RlPWRpc2FibGU=
